apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference-service
spec:
  # 2 replicas, this is our scaling requirement satisfied. Two copies of inference run at once, and Kubernetes' Service (below) automatically splits incoming requests between them
  replicas: 2
  selector:
    matchLabels:
      app: ai-inference-service
  template:
    metadata:
      labels:
        app: ai-inference-service
    spec:
      containers:
        - name: ai-inference-service
          # Pulls the image we built and pushed to Docker Hub
          image: yixinn/egt307-ai-inference-service:latest
          ports:
            - containerPort: 8000
          # Resource requests/limits, required for the HPA to actually calculate a CPU usage percentage. Without this, there's nothing for autoscaling to measure against
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "500m"
          env:
            # Username and password from the Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASS
            # Host and database name from the ConfigMap
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: ai-inference-service
spec:
  selector:
    app: ai-inference-service
  ports:
    - port: 8000
      targetPort: 8000