apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-inference-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-inference-service
  template:
    metadata:
      labels:
        app: ai-inference-service
    spec:
      containers:
        - name: ai-inference-service
          image: yixinn/egt307-ai-inference-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: ai-inference-service
spec:
  selector:
    app: ai-inference-service
  ports:
    - port: 8000
      targetPort: 8000