apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  aqi_pass: "PASTE_YOUR_SCRAMBLED_STRING_HERE" 
  # (If you also want to hide the username 'aqi_user', you can base64 encode that too and add it here!)